import pandas as pd
from pymongo import MongoClient

from heliolib.mongo_db_client import (
    MongoDBClient,
)


def test_validate_query_params_valid():
    # Test with valid query parameters
    valid_params = {
        "plantId": "123",
        "inverter_id": "456",
        "mppt_id": "789",
        "string_id": "101112",
        "fault_name": "Fault1",
        "string_date": "2023-01-01",
        "date": pd.Timestamp("2023-01-01"),
    }
    try:
        mongo_client = MongoDBClient(mongo_client=MongoClient("mongo_url"))
        mongo_client._validate_query_params(valid_params)
    except Exception as e:
        raise f"Unexpected exception raised: {e}"


def test_validate_query_params_with_invalid_date_param():
    # Test with invalid query parameters
    invalid_params = {
        "plantId": "123",  # Should be a string
        "date": "2023-01-01",  # Should be a pd.Timestamp
    }

    try:
        mongo_client = MongoDBClient(mongo_client=MongoClient("mongo_url"))
        mongo_client._validate_query_params(invalid_params)
    except Exception as e:
        assert str(e) == "Parameter date must be a type pd.Timestamp"
